#ifndef _MSG_IDS_HG_
#define _MSG_IDS_HG_

enum messageIDs {
    JOIN_ROOM = 1,
    LEAVE_ROOM,
    SEND_TEXT,
    CREATE_ACCOUNT,
    AUTHENTICATE,
    VALIDATE_SERVER,
    CREATE_ACCOUNT_WEB,
    CREATE_ACCOUNT_WEB_SUCCESS,
    CREATE_ACCOUNT_WEB_FAILURE,
    AUTHENTICATE_WEB,
    AUTHENTICATE_WEB_SUCCESS,
    AUTHENTICATE_WEB_FAILURE
};

#endif 
